<?php

namespace Internshala\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class InternshalaModelsSchool_ContactinfoProxy extends \Internshala\Models\School_Contactinfo implements \Doctrine\ORM\Proxy\Proxy {

    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;

    public function __construct($entityPersister, $identifier) {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }

    /** @private */
    public function __load() {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    public function id() {
        $this->__load();
        return parent::id();
    }

    public function set_school(\Internshala\Models\School $school) {
        $this->__load();
        return parent::set_school($school);
    }

    public function school() {
        $this->__load();
        return parent::school();
    }

    public function set_address($address) {
        $this->__load();
        return parent::set_address($address);
    }

    public function address() {
        $this->__load();
        return parent::address();
    }

    public function set_email($email) {
        $this->__load();
        return parent::set_email($email);
    }

    public function email() {
        $this->__load();
        return parent::email();
    }

    public function set_email_2($email_2) {
        $this->__load();
        return parent::set_email_2($email_2);
    }

    public function email_2() {
        $this->__load();
        return parent::email_2();
    }
    
    public function set_contact_info($contact_info) {
        $this->__load();
        return parent::set_contact_info($contact_info);
    }

    public function contact_info() {
        $this->__load();
        return parent::contact_info();
    }

    public function set_phone($phone) {
        $this->__load();
        return parent::set_phone($phone);
    }

    public function phone() {
        $this->__load();
        return parent::phone();
    }
    
    public function set_contact_info_2($contact_info_2) {
        $this->__load();
        return parent::set_contact_info_2($contact_info_2);
    }

    public function contact_info_2() {
        $this->__load();
        return parent::contact_info_2();
    }

    public function set_phone_2($phone_2) {
        $this->__load();
        return parent::set_phone_2($phone_2);
    }

    public function phone_2() {
        $this->__load();
        return parent::phone_2();
    }

    public function set_website($website) {
        $this->__load();
        return parent::set_website($website);
    }

    public function website() {
        $this->__load();
        return parent::website();
    }

    public function set_created_at($created_at) {
        $this->__load();
        return parent::set_created_at($created_at);
    }

    public function created_at() {
        $this->__load();
        return parent::created_at();
    }

    public function set_last_updated_at($last_updated_at) {
        $this->__load();
        return parent::set_last_updated_at($last_updated_at);
    }

    public function last_updated_at() {
        $this->__load();
        return parent::last_updated_at();
    }

    public function __toString() {
        $this->__load();
        return parent::__toString();
    }

    public function &to_array() {
        $this->__load();
        return parent::to_array();
    }

    public function on_pre_presist() {
        $this->__load();
        return parent::on_pre_presist();
    }

    public function on_pre_update() {
        $this->__load();
        return parent::on_pre_update();
    }

    public function on_pre_remove() {
        $this->__load();
        return parent::on_pre_remove();
    }

    public function on_post_load() {
        $this->__load();
        return parent::on_post_load();
    }

    public function __sleep() {
        return array('__isInitialized__', 'id', 'school', 'email', 'email_2', 'country_code', 'phone', 'country_code_2', 'phone_2', 'website', 'created_at', 'last_updated_at');
    }

    public function __clone() {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

}
