<?php

namespace Meetschools\Proxies;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class MeetschoolsModelsUserProxy extends \Meetschools\Models\User implements \Doctrine\ORM\Proxy\Proxy {

    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;

    public function __construct($entityPersister, $identifier) {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }

    /** @private */
    public function __load() {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    public function id() {
        $this->__load();
        return parent::id();
    }

    public function set_email($email) {
        $this->__load();
        return parent::set_email($email);
    }

    public function email() {
        $this->__load();
        return parent::email();
    }

    public function set_password($password) {
        $this->__load();
        return parent::set_password($password);
    }

    public function password() {
        $this->__load();
        return parent::password();
    }

    public function set_type($type) {
        $this->__load();
        return parent::set_type($type);
    }

    public function type() {
        $this->__load();
        return parent::type();
    }

    public function set_status($status) {
        $this->__load();
        return parent::set_status($status);
    }

    public function status() {
        $this->__load();
        return parent::status();
    }

    public function set_unique_key($unique_key) {
        $this->__load();
        return parent::set_unique_key($unique_key);
    }

    public function unique_key() {
        $this->__load();
        return parent::unique_key();
    }

    public function set_last_seen_at($last_seen_at) {
        $this->__load();
        return parent::set_last_seen_at($last_seen_at);
    }

    public function last_seen_at() {
        $this->__load();
        return parent::last_seen_at();
    }

    public function set_last_login_at($last_login_at) {
        $this->__load();
        return parent::set_last_login_at($last_login_at);
    }

    public function last_login_at() {
        $this->__load();
        return parent::last_login_at();
    }

    public function set_created_at($created_at) {
        $this->__load();
        return parent::set_created_at($created_at);
    }

    public function created_at() {
        $this->__load();
        return parent::created_at();
    }

    public function set_last_updated_at($last_updated_at) {
        $this->__load();
        return parent::set_last_updated_at($last_updated_at);
    }

    public function last_updated_at() {
        $this->__load();
        return parent::last_updated_at();
    }

    public function add_subscriber(\Meetschools\Models\Subscriber $subscriber) {
        $this->__load();
        return parent::add_subscriber($subscriber);
    }

    public function subscriber() {
        $this->__load();
        return parent::subscriber();
    }

    public function add_student(\Meetschools\Models\Student $student) {
        $this->__load();
        return parent::add_student($student);
    }

    public function student() {
        $this->__load();
        return parent::student();
    }

    public function __toString() {
        $this->__load();
        return parent::__toString();
    }

    public function &to_array() {
        $this->__load();
        return parent::to_array();
    }

    public function on_pre_presist() {
        $this->__load();
        return parent::on_pre_presist();
    }

    public function on_pre_update() {
        $this->__load();
        return parent::on_pre_update();
    }

    public function on_pre_remove() {
        $this->__load();
        return parent::on_pre_remove();
    }

    public function on_post_load() {
        $this->__load();
        return parent::on_post_load();
    }

    public function __sleep() {
        return array('__isInitialized__', 'id', 'email', 'password', 'type', 'status', 'unique_key', 'last_seen_at', 'last_login_at', 'created_at', 'last_updated_at', 'subscriber', 'student');
    }

    public function __clone() {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

}
