<?php
/*************************************************************************
DO NOT EDIT THIS FILE
THIS IS AUTO GENERATED FROM email.php
*************************************************************************/
?><?php

    $config['useragent'] = 'meetschools.com';
    
    $config['protocol'] = 'smtp';
    
    $config['mailpath'] = '';
    
    $config['smtp_host'] = 'ssl://email-smtp.us-east-1.amazonaws.com';
    $config['smtp_user'] = 'smtp_user';
    
    $config['smtp_pass'] = 'smtp_pass';
    
    $config['smtp_port'] = '465';
    
    $config['validate'] = TRUE;
    
    $config['crlf'] = "\n";
    
    $config['newline'] = "\r\n";
    
    $config['default_headers'] = array(
        'From' => '"' . addcslashes('Meetschools', "\0..\37\177'\"\\") . '"' . ' <no-reply@meetschools.com>',
        'Return-Path' => '<no-reply@meetschools.com>'
    );

/* End of file email.php */
/* Location: ./application/config/email.php */
